// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package com.phonepe.platform.es.replicator.grpc.events;

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChangeEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChangeEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.SerializedTranslog translog = 1;</code>
     * @return Whether the translog field is set.
     */
    boolean hasTranslog();
    /**
     * <code>.SerializedTranslog translog = 1;</code>
     * @return The translog.
     */
    com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog getTranslog();
    /**
     * <code>.SerializedTranslog translog = 1;</code>
     */
    com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslogOrBuilder getTranslogOrBuilder();

    /**
     * <code>int64 connectorSentTimestamp = 2;</code>
     * @return The connectorSentTimestamp.
     */
    long getConnectorSentTimestamp();
  }
  /**
   * Protobuf type {@code ChangeEvent}
   */
  public static final class ChangeEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChangeEvent)
      ChangeEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChangeEvent.newBuilder() to construct.
    private ChangeEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChangeEvent() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChangeEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChangeEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog.Builder subBuilder = null;
              if (translog_ != null) {
                subBuilder = translog_.toBuilder();
              }
              translog_ = input.readMessage(com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(translog_);
                translog_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              connectorSentTimestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.phonepe.platform.es.replicator.grpc.events.Events.internal_static_ChangeEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.phonepe.platform.es.replicator.grpc.events.Events.internal_static_ChangeEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent.class, com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent.Builder.class);
    }

    public static final int TRANSLOG_FIELD_NUMBER = 1;
    private com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog translog_;
    /**
     * <code>.SerializedTranslog translog = 1;</code>
     * @return Whether the translog field is set.
     */
    @java.lang.Override
    public boolean hasTranslog() {
      return translog_ != null;
    }
    /**
     * <code>.SerializedTranslog translog = 1;</code>
     * @return The translog.
     */
    @java.lang.Override
    public com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog getTranslog() {
      return translog_ == null ? com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog.getDefaultInstance() : translog_;
    }
    /**
     * <code>.SerializedTranslog translog = 1;</code>
     */
    @java.lang.Override
    public com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslogOrBuilder getTranslogOrBuilder() {
      return getTranslog();
    }

    public static final int CONNECTORSENTTIMESTAMP_FIELD_NUMBER = 2;
    private long connectorSentTimestamp_;
    /**
     * <code>int64 connectorSentTimestamp = 2;</code>
     * @return The connectorSentTimestamp.
     */
    @java.lang.Override
    public long getConnectorSentTimestamp() {
      return connectorSentTimestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (translog_ != null) {
        output.writeMessage(1, getTranslog());
      }
      if (connectorSentTimestamp_ != 0L) {
        output.writeInt64(2, connectorSentTimestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (translog_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTranslog());
      }
      if (connectorSentTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, connectorSentTimestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent)) {
        return super.equals(obj);
      }
      com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent other = (com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent) obj;

      if (hasTranslog() != other.hasTranslog()) return false;
      if (hasTranslog()) {
        if (!getTranslog()
            .equals(other.getTranslog())) return false;
      }
      if (getConnectorSentTimestamp()
          != other.getConnectorSentTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTranslog()) {
        hash = (37 * hash) + TRANSLOG_FIELD_NUMBER;
        hash = (53 * hash) + getTranslog().hashCode();
      }
      hash = (37 * hash) + CONNECTORSENTTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getConnectorSentTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChangeEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChangeEvent)
        com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.phonepe.platform.es.replicator.grpc.events.Events.internal_static_ChangeEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.phonepe.platform.es.replicator.grpc.events.Events.internal_static_ChangeEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent.class, com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent.Builder.class);
      }

      // Construct using com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (translogBuilder_ == null) {
          translog_ = null;
        } else {
          translog_ = null;
          translogBuilder_ = null;
        }
        connectorSentTimestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.phonepe.platform.es.replicator.grpc.events.Events.internal_static_ChangeEvent_descriptor;
      }

      @java.lang.Override
      public com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent getDefaultInstanceForType() {
        return com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent build() {
        com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent buildPartial() {
        com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent result = new com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent(this);
        if (translogBuilder_ == null) {
          result.translog_ = translog_;
        } else {
          result.translog_ = translogBuilder_.build();
        }
        result.connectorSentTimestamp_ = connectorSentTimestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent) {
          return mergeFrom((com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent other) {
        if (other == com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent.getDefaultInstance()) return this;
        if (other.hasTranslog()) {
          mergeTranslog(other.getTranslog());
        }
        if (other.getConnectorSentTimestamp() != 0L) {
          setConnectorSentTimestamp(other.getConnectorSentTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog translog_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog, com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog.Builder, com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslogOrBuilder> translogBuilder_;
      /**
       * <code>.SerializedTranslog translog = 1;</code>
       * @return Whether the translog field is set.
       */
      public boolean hasTranslog() {
        return translogBuilder_ != null || translog_ != null;
      }
      /**
       * <code>.SerializedTranslog translog = 1;</code>
       * @return The translog.
       */
      public com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog getTranslog() {
        if (translogBuilder_ == null) {
          return translog_ == null ? com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog.getDefaultInstance() : translog_;
        } else {
          return translogBuilder_.getMessage();
        }
      }
      /**
       * <code>.SerializedTranslog translog = 1;</code>
       */
      public Builder setTranslog(com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog value) {
        if (translogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          translog_ = value;
          onChanged();
        } else {
          translogBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.SerializedTranslog translog = 1;</code>
       */
      public Builder setTranslog(
          com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog.Builder builderForValue) {
        if (translogBuilder_ == null) {
          translog_ = builderForValue.build();
          onChanged();
        } else {
          translogBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.SerializedTranslog translog = 1;</code>
       */
      public Builder mergeTranslog(com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog value) {
        if (translogBuilder_ == null) {
          if (translog_ != null) {
            translog_ =
              com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog.newBuilder(translog_).mergeFrom(value).buildPartial();
          } else {
            translog_ = value;
          }
          onChanged();
        } else {
          translogBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.SerializedTranslog translog = 1;</code>
       */
      public Builder clearTranslog() {
        if (translogBuilder_ == null) {
          translog_ = null;
          onChanged();
        } else {
          translog_ = null;
          translogBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.SerializedTranslog translog = 1;</code>
       */
      public com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog.Builder getTranslogBuilder() {
        
        onChanged();
        return getTranslogFieldBuilder().getBuilder();
      }
      /**
       * <code>.SerializedTranslog translog = 1;</code>
       */
      public com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslogOrBuilder getTranslogOrBuilder() {
        if (translogBuilder_ != null) {
          return translogBuilder_.getMessageOrBuilder();
        } else {
          return translog_ == null ?
              com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog.getDefaultInstance() : translog_;
        }
      }
      /**
       * <code>.SerializedTranslog translog = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog, com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog.Builder, com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslogOrBuilder> 
          getTranslogFieldBuilder() {
        if (translogBuilder_ == null) {
          translogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog, com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslog.Builder, com.phonepe.platform.es.replicator.grpc.Engine.SerializedTranslogOrBuilder>(
                  getTranslog(),
                  getParentForChildren(),
                  isClean());
          translog_ = null;
        }
        return translogBuilder_;
      }

      private long connectorSentTimestamp_ ;
      /**
       * <code>int64 connectorSentTimestamp = 2;</code>
       * @return The connectorSentTimestamp.
       */
      @java.lang.Override
      public long getConnectorSentTimestamp() {
        return connectorSentTimestamp_;
      }
      /**
       * <code>int64 connectorSentTimestamp = 2;</code>
       * @param value The connectorSentTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setConnectorSentTimestamp(long value) {
        
        connectorSentTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 connectorSentTimestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnectorSentTimestamp() {
        
        connectorSentTimestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChangeEvent)
    }

    // @@protoc_insertion_point(class_scope:ChangeEvent)
    private static final com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent();
    }

    public static com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChangeEvent>
        PARSER = new com.google.protobuf.AbstractParser<ChangeEvent>() {
      @java.lang.Override
      public ChangeEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChangeEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChangeEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChangeEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.phonepe.platform.es.replicator.grpc.events.Events.ChangeEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangeEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangeEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014events.proto\032\014engine.proto\"T\n\013ChangeEv" +
      "ent\022%\n\010translog\030\001 \001(\0132\023.SerializedTransl" +
      "og\022\036\n\026connectorSentTimestamp\030\002 \001(\003B2\n.co" +
      "m.phonepe.platform.es.replicator.grpc.ev" +
      "entsP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.phonepe.platform.es.replicator.grpc.Engine.getDescriptor(),
        });
    internal_static_ChangeEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChangeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangeEvent_descriptor,
        new java.lang.String[] { "Translog", "ConnectorSentTimestamp", });
    com.phonepe.platform.es.replicator.grpc.Engine.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
